[2022-03-23 08:20:21,433] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2022-03-23T08:20:12.576188+00:00 [queued]>
[2022-03-23 08:20:21,481] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2022-03-23T08:20:12.576188+00:00 [queued]>
[2022-03-23 08:20:21,482] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 08:20:21,483] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2022-03-23 08:20:21,483] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 08:20:21,694] {taskinstance.py:900} INFO - Executing <Task(GoogleCloudStorageToBigQueryOperator): load_data> on 2022-03-23T08:20:12.576188+00:00
[2022-03-23 08:20:21,699] {standard_task_runner.py:53} INFO - Started process 6163 to run task
[2022-03-23 08:20:22,036] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.load_data 2022-03-23T08:20:12.576188+00:00 [running]> DESKTOP-NRCNVOU.localdomain
[2022-03-23 08:20:23,119] {logging_mixin.py:112} INFO - [2022-03-23 08:20:23,118] {http.py:126} WARNING - Encountered 403 Forbidden with reason "accessDenied"
[2022-03-23 08:20:23,120] {taskinstance.py:1145} ERROR - <HttpError 403 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/dmc-airflow-tutorial-demo/jobs?alt=json returned "Access Denied: Project dmc-airflow-tutorial-demo: User does not have bigquery.jobs.create permission in project dmc-airflow-tutorial-demo.". Details: "Access Denied: Project dmc-airflow-tutorial-demo: User does not have bigquery.jobs.create permission in project dmc-airflow-tutorial-demo.">
Traceback (most recent call last):
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/operators/gcs_to_bq.py", line 268, in execute
    cursor.run_load(
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1297, in run_load
    return self.run_with_configuration(configuration)
  File "/home/collid/.local/lib/python3.8/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1316, in run_with_configuration
    query_reply = jobs \
  File "/home/collid/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/collid/.local/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/dmc-airflow-tutorial-demo/jobs?alt=json returned "Access Denied: Project dmc-airflow-tutorial-demo: User does not have bigquery.jobs.create permission in project dmc-airflow-tutorial-demo.". Details: "Access Denied: Project dmc-airflow-tutorial-demo: User does not have bigquery.jobs.create permission in project dmc-airflow-tutorial-demo.">
[2022-03-23 08:20:23,129] {taskinstance.py:1189} INFO - Marking task as FAILED.dag_id=bigquery_data_load, task_id=load_data, execution_date=20220323T082012, start_date=20220323T082021, end_date=20220323T082023
[2022-03-23 08:20:31,295] {logging_mixin.py:112} INFO - [2022-03-23 08:20:31,294] {local_task_job.py:103} INFO - Task exited with return code 1
